import os
import json

import numpy as np
import cv2
import pandas as pd
import streamlit as st
import tensorflow as tf
from skimage.measure import label as sk_label, regionprops
from skimage.feature import graycomatrix, graycoprops

# ----------------------------------------------------------------------------
# Page setup
# ----------------------------------------------------------------------------
st.set_page_config(page_title="UHCS Micrograph Phase Identification", layout="wide")

MODEL_DIR = os.path.join(os.path.dirname(__file__), "models")
SAMPLE_DIR = os.path.join(os.path.dirname(__file__), "sample_images")


@st.cache_resource(show_spinner="Loading models...")
def load_models():
    unet = tf.keras.models.load_model(
        os.path.join(MODEL_DIR, "unet_model.keras"), compile=False
    )
    clf = tf.keras.models.load_model(
        os.path.join(MODEL_DIR, "classifier_model.keras"), compile=False
    )
    with open(os.path.join(MODEL_DIR, "label_classes.json")) as f:
        classes = json.load(f)
    with open(os.path.join(MODEL_DIR, "config.json")) as f:
        config = json.load(f)
    img_size = tuple(config["img_size"])
    return unet, clf, classes, img_size


def extract_features(gray_uint8, mask_uint8):
    area_fraction = mask_uint8.mean()

    lbl = sk_label(mask_uint8)
    props = [p for p in regionprops(lbl) if p.area >= 3]
    sizes = [p.equivalent_diameter_area for p in props]
    mean_particle_size = float(np.mean(sizes)) if sizes else 0.0
    particle_count = len(props)
    particle_density = particle_count / mask_uint8.size

    glcm = graycomatrix(
        gray_uint8, distances=[1], angles=[0], levels=256, symmetric=True, normed=True
    )
    glcm_contrast = float(graycoprops(glcm, "contrast")[0, 0])

    return {
        "Phase area fraction": round(float(area_fraction), 4),
        "Mean particle size (px)": round(mean_particle_size, 2),
        "Particle count": particle_count,
        "Particle density": round(particle_density, 6),
        "GLCM contrast": round(glcm_contrast, 2),
    }


def analyze(gray_uint8_full_res, unet, clf, classes, img_size):
    gray = cv2.resize(gray_uint8_full_res, img_size, interpolation=cv2.INTER_AREA)
    x = (gray.astype("float32") / 255.0)[None, ..., None]

    pred_mask = (unet.predict(x, verbose=0)[0, ..., 0] > 0.5).astype("uint8")

    class_probs = clf.predict(x, verbose=0)[0]
    pred_class = classes[int(np.argmax(class_probs))]
    confidence = float(np.max(class_probs))

    feats = extract_features(gray, pred_mask)

    return gray, pred_mask, pred_class, confidence, feats, class_probs


# ----------------------------------------------------------------------------
# UI
# ----------------------------------------------------------------------------
st.title("UHCS Micrograph Phase Identification")
st.caption(
    "Upload an ultra-high-carbon-steel micrograph to get a phase segmentation, "
    "a predicted microconstituent class, and 4 quantitative microstructural parameters."
)

with st.expander("About this system / honesty note on model performance", expanded=False):
    st.markdown(
        """
This tool chains two models trained on the [UHCSDB dataset](https://www.kaggle.com/datasets/safi842/highcarbon-micrographs)
(Carnegie Mellon University):

- **U-Net segmentation** — trained on pseudo-masks generated by classical Otsu thresholding,
  since the dataset has no human-annotated pixel masks. Validation Dice ≈ 0.85 against those
  pseudo-masks — a measure of how well the network reproduces the classical method, not a
  validated ground-truth segmentation score.
- **CNN classifier** — trained on real expert-provided microconstituent labels. Test accuracy
  ≈ 60%, but the dataset is heavily imbalanced (one class has 372 examples, another has 5), so
  rare-class predictions should be treated with caution.

Full details, training curves, and the complete evaluation are in the companion notebook and SRS
document in this repository.
"""
    )

unet, clf, classes, img_size = load_models()

st.subheader("1. Choose an image")
col_a, col_b = st.columns([2, 1])
with col_a:
    uploaded = st.file_uploader("Upload a micrograph (PNG/JPG)", type=["png", "jpg", "jpeg"])
with col_b:
    sample_files = sorted(os.listdir(SAMPLE_DIR)) if os.path.isdir(SAMPLE_DIR) else []
    sample_choice = st.selectbox("...or try a sample image", ["(none)"] + sample_files)

gray_full = None
source_name = None

if uploaded is not None:
    file_bytes = np.frombuffer(uploaded.read(), dtype=np.uint8)
    gray_full = cv2.imdecode(file_bytes, cv2.IMREAD_GRAYSCALE)
    source_name = uploaded.name
elif sample_choice != "(none)":
    gray_full = cv2.imread(os.path.join(SAMPLE_DIR, sample_choice), cv2.IMREAD_GRAYSCALE)
    source_name = sample_choice

if gray_full is not None:
    st.subheader("2. Results")
    gray, mask, pred_class, confidence, feats, probs = analyze(
        gray_full, unet, clf, classes, img_size
    )

    col1, col2 = st.columns(2)
    with col1:
        st.image(gray, caption=f"Input: {source_name}", use_container_width=True, clamp=True)
    with col2:
        st.image(
            (mask * 255).astype("uint8"),
            caption="Predicted phase mask (U-Net)",
            use_container_width=True,
            clamp=True,
        )

    st.markdown(f"**Predicted microconstituent:** `{pred_class}`  (confidence {confidence:.1%})")

    prob_df = pd.DataFrame({"Class": classes, "Probability": probs}).sort_values(
        "Probability", ascending=False
    )
    st.bar_chart(prob_df.set_index("Class"))

    st.markdown("**Quantitative features (from the predicted mask):**")
    feat_df = pd.DataFrame(feats.items(), columns=["Feature", "Value"])
    st.table(feat_df)
else:
    st.info("Upload an image or pick a sample to run the analysis.")

st.divider()
st.caption(
    "Models: U-Net (segmentation, trained on classical-threshold pseudo-masks) + "
    "CNN (classification, trained on real expert labels). See the SRS document for full "
    "requirements and the notebook for the full training/evaluation pipeline."
)
